INSERT INTO work_orders (id, employee_id, title, description) VALUES
(1, 3, 'Inspect conveyor belt system', 'Perform visual inspection of conveyor belt system for wear, damage, and proper tension. Check for any loose components or unusual noises during operation.'),
(2, 7, 'Replace hydraulic pump filter', 'Remove and replace the hydraulic pump filter in the main production line. Clean the filter housing and ensure proper seal installation.'),
(3, 2, 'Calibrate temperature sensors', 'Calibrate all temperature sensors in the heat treatment oven. Verify readings against reference thermometer and adjust as needed.'),
(4, 9, 'Lubricate robotic arm joints', 'Apply appropriate lubricant to all robotic arm joints and check for smooth movement. Inspect for any signs of excessive wear.'),
(5, 4, 'Check electrical panel connections', 'Inspect all electrical panel connections for tightness and signs of overheating. Clean any dust buildup and verify proper grounding.'),
(6, 1, 'Test emergency stop system', 'Perform functional test of all emergency stop buttons throughout the facility. Verify proper shutdown sequence and alarm activation.'),
(7, 8, 'Replace worn cutting tools', 'Remove and replace worn cutting tools on CNC machine #3. Adjust tool offsets and verify cutting accuracy with test piece.'),
(8, 5, 'Clean coolant filtration system', 'Drain and clean the coolant filtration system. Replace filter elements and refill with fresh coolant mixture.'),
(9, 6, 'Inspect safety guards', 'Check all machine safety guards for proper installation and functionality. Ensure interlock switches are working correctly.'),
(10, 10, 'Monitor vibration levels', 'Use vibration analyzer to check motor and bearing vibration levels on production equipment. Document readings for trend analysis.'),
(11, 3, 'Replace air compressor filters', 'Remove and replace air compressor intake and oil filters. Check oil level and drain any accumulated moisture.'),
(12, 7, 'Calibrate pressure gauges', 'Calibrate all pressure gauges in the hydraulic system against a certified reference standard.'),
(13, 2, 'Inspect welding equipment', 'Check welding equipment for proper gas flow, wire feed, and electrical connections. Clean torch and replace consumables if needed.'),
(14, 9, 'Test backup power system', 'Run backup generator test and verify automatic transfer switch operation. Check fuel levels and battery condition.'),
(15, 4, 'Replace worn bearings', 'Remove and replace worn bearings in the main drive shaft. Align shaft and verify smooth operation.'),
(16, 1, 'Clean ventilation ducts', 'Remove and clean ventilation ducts in the paint booth. Replace filters and check fan operation.'),
(17, 8, 'Inspect hydraulic hoses', 'Check all hydraulic hoses for signs of wear, cracking, or leakage. Replace any damaged hoses immediately.'),
(18, 5, 'Test fire suppression system', 'Perform monthly test of fire suppression system in the paint booth. Verify all nozzles are clear and pressurized.'),
(19, 6, 'Calibrate flow meters', 'Calibrate all flow meters in the coolant and lubrication systems using certified calibration equipment.'),
(20, 10, 'Replace worn belts', 'Replace worn drive belts on conveyor system. Adjust tension and verify proper alignment.'),
(21, 3, 'Inspect electrical motors', 'Perform thermal imaging scan of all electrical motors. Check for hot spots and unusual vibration patterns.'),
(22, 7, 'Clean heat exchanger', 'Remove and clean heat exchanger tubes in the cooling system. Check for corrosion and replace damaged tubes.'),
(23, 2, 'Test control panel functions', 'Test all control panel functions and verify proper operation of all switches, indicators, and displays.'),
(24, 9, 'Replace worn seals', 'Replace worn seals in hydraulic cylinders. Check for proper installation and test for leaks.'),
(25, 4, 'Inspect crane operation', 'Test overhead crane operation including hoist, trolley, and bridge movement. Check limit switches and emergency stops.'),
(26, 1, 'Clean compressed air lines', 'Drain moisture from compressed air lines and clean filters. Check for leaks and repair as needed.'),
(27, 8, 'Test safety interlocks', 'Verify all safety interlocks are functioning properly on automated equipment. Test emergency shutdown procedures.'),
(28, 5, 'Replace worn gears', 'Remove and replace worn gears in the main transmission. Check alignment and verify proper lubrication.'),
(29, 6, 'Inspect electrical grounding', 'Check electrical grounding connections throughout the facility. Verify resistance readings are within specifications.'),
(30, 10, 'Test backup alarms', 'Test all backup alarm systems including fire alarms, gas detection, and emergency notification systems.'); 