name: 📄 Task
description: Create a task
labels: [task]
body:
- type: markdown
  attributes:
    value: |
      A task is a discrete piece of work that needs doing that doesn't necessarily
      related to a Story or Epic.
- type: textarea
  attributes:
    label: Description
    description: Describe the task
- type: input
  attributes:
    label: Epic/Story
    description: Is this task part of an existing epic or story?
    placeholder: '#123'
- type: dropdown
  id: estimation
  attributes:
    label: Have you provided an initial effort estimate for this issue?
    description: See our [handbook](https://flowforge.com/handbook/development/releases/planning/#effort-estimation) for more details.
    multiple: false
    options:
      - I have provided an initial effort estimate
      - I am not a FlowForge team member
      - I can not provide an initial effort estimate
  validations:
      required: true
