import { readdirSync, statSync } from 'node:fs'
import { join, basename } from 'node:path'
import remarkHandbookLinks from './utils/remark-handbook-links'
import remarkDocsLinks from './utils/remark-docs-links'

// Collect all handbook routes from content files for SSG prerendering
function collectHandbookRoutes(dir: string, basePath: string): string[] {
    const routes: string[] = []
    for (const file of readdirSync(dir)) {
        const fullPath = join(dir, file)
        if (statSync(fullPath).isDirectory()) {
            routes.push(...collectHandbookRoutes(fullPath, `${basePath}/${file}`))
        } else if (file.endsWith('.md')) {
            const slug = basename(file, '.md')
            routes.push(slug === 'index' ? `${basePath}/` : `${basePath}/${slug}/`)
        }
    }
    return routes
}

// Same idea for changelog entries, plus the paginated listing (19 entries/page, newest first)
function collectChangelogRoutes(dir: string, basePath: string): { routes: string[], entryCount: number } {
    const routes: string[] = []
    let entryCount = 0
    for (const file of readdirSync(dir)) {
        const fullPath = join(dir, file)
        if (statSync(fullPath).isDirectory()) {
            const nested = collectChangelogRoutes(fullPath, `${basePath}/${file}`)
            routes.push(...nested.routes)
            entryCount += nested.entryCount
        } else if (file.endsWith('.md')) {
            entryCount += 1
            routes.push(`${basePath}/${basename(file, '.md')}/`)
        }
    }
    return { routes, entryCount }
}

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    devtools: { enabled: true },
    modules: ['@nuxt/ui', '@nuxt/content', '@nuxtjs/seo', 'nuxt-studio', '@nuxt/image', './modules/docs-source'],

    // Captured at build time (Netlify sets CONTEXT during the build, not necessarily
    // in the deployed Function's runtime), then baked into the server bundle via
    // runtimeConfig so analytics.ts doesn't depend on a process.env read at request time.
    runtimeConfig: {
        isProductionContext: process.env.CONTEXT === 'production'
    },

    css: ['~/assets/css/theme.css'],

    // Heebo is already loaded via the Google Fonts <link> in app.head.
    // @nuxt/fonts is a transitive dep of @nuxt/ui; disable all provider downloads
    // so it never fetches font files at build time (which exhausts Netlify's memory).
    fonts: { providers: { google: false, bunny: false, fontshare: false, adobe: false } },

    site: {
        url: 'https://flowfuse.com',
        name: 'FlowFuse',
        description: 'Low-code application development platform for Node-RED and industrial IoT.',
        defaultLocale: 'en',
    },

    sitemap: {
        sources: [
            // Nuxt-native dynamic routes (integrations) that
            // @nuxtjs/seo's static-route auto-discovery can't see
            '/api/__sitemap__/dynamic-urls',
        ],
        exclude: ['/_studio/**', '/api/**'],
    },

    robots: {
        groups: [
            { userAgent: ['*'], allow: ['/'] },
            { userAgent: ['Algolia Crawler'], allow: ['/'] },
        ],
        // sitemap.xml covers Nuxt-native pages; sitemap-legacy.xml (generated by 11ty,
        // served as a static file from nuxt/public/) covers everything still on 11ty.
        sitemap: ['https://flowfuse.com/sitemap.xml', 'https://flowfuse.com/sitemap-legacy.xml'],
    },

    linkChecker: {
        failOnError: true,
        // trailing-slash: 11ty pages use trailing slashes intentionally
        // no-error-response: links to 11ty pages return 404 in the Nuxt-only static output
        skipInspections: ['trailing-slash', 'no-error-response'],
    },

    // @nuxt/content generates import statements for remark plugin keys.
    // These aliases make them resolvable in the Vite bundle context.
    alias: {
        'handbook-links': join(__dirname, 'utils/remark-handbook-links'),
        'docs-links': join(__dirname, 'utils/remark-docs-links'),
    },

    app: {
        head: {
            link: [
                { rel: 'stylesheet', href: '/css/style.css' },
                { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
                { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
                { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Heebo:wght@100..900&display=swap' },
                { rel: 'stylesheet', href: 'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css', integrity: 'sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+', crossorigin: 'anonymous' },
                { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
                { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' },
                { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' },
                { rel: 'mask-icon', href: '/safari-pinned-tab.svg', color: '#aa4444' },
            ],
            meta: [
                { name: 'msapplication-TileColor', content: '#00aba9' },
                { name: 'theme-color', content: '#ffffff' },
            ]
        }
    },

    image: {
        // The Netlify image provider proxies through a Netlify Image CDN function that only
        // exists on deployed/Netlify-run infra, so it 404s under plain `nuxt dev`. Fall back to
        // the passthrough provider outside production builds, or when SKIP_IMAGES is set.
        provider: (process.env.NODE_ENV !== 'production' || process.env.SKIP_IMAGES === 'true') ? 'none' : 'netlify',
        domains: ['flowfuse.com', 'www.flowfuse.com'],
        quality: 80,
    },

    routeRules: {
        '/terms': { robots: false },
        '/privacy-policy': { robots: false },
    },

    nitro: {
        preset: 'netlify',
        serverAssets: [
            {
                baseName: 'analytics',
                // Nitro resolves this dir against nitro.srcDir (Nuxt's serverDir, i.e. nuxt/server),
                // not against the nuxt/ root — so this needs one more level up than it looks like.
                dir: '../../src/_includes/analytics'
            },
            {
                baseName: 'team',
                dir: '../src/_data/team'
            },
            {
                baseName: 'guests',
                dir: '../src/_data/guests'
            }
        ],
        prerender: {
            routes: (() => {
                const changelog = collectChangelogRoutes(join(__dirname, '../src/changelog'), '/changelog')
                const changelogPageCount = Math.max(1, Math.ceil(changelog.entryCount / 19))
                const changelogListingRoutes = ['/changelog/', ...Array.from({ length: changelogPageCount - 1 }, (_, i) => `/changelog/${i + 2}/`)]
                return [
                    '/terms',
                    '/privacy-policy',
                    '/integrations',
                    '/pricing',
                    '/ebooks/beginner-guide-to-a-professional-nodered/',
                    '/ebooks/ultimate-guide-to-building-applications-with-flowfuse-dashboard-for-node-red/',
                    '/whitepaper/uns-decoupling-data-producers-and-consumers/',
                    '/whitepaper/open-source-software-for-manufacturing/',
                    '/whitepaper/accelerating-innovation-in-manufacturing-with-flowfuse/',
                    '/whitepaper/accelerating-industrial-innovation-with-low-code-platforms/',
                    '/resources/publications/',
                    '/changelog/index.xml',
                    ...changelogListingRoutes,
                    ...changelog.routes,
                    ...collectHandbookRoutes(join(__dirname, 'content/handbook'), '/handbook'),
                ]
            })(),
            crawlLinks: false
        }
    },

    hooks: {
        // Enumerate /integrations/{id}/ routes at config-time so SSG prerenders them.
        // Can't use Nuxt's $fetch here — it only exists at nitro runtime.
        async 'nitro:config' (nitroConfig: import('nitropack').NitroConfig) {
            if (nitroConfig.dev) return
            const { buildEnrichedIntegrations } = await import('./server/utils/integrations-enrich')
            const integrations = await buildEnrichedIntegrations()
            if (integrations.length === 0) {
                throw new Error('[nuxt] integrations enumeration returned 0 nodes — refusing to build a site with no detail pages')
            }
            const routes = integrations.map(node => `/integrations/${node._id}/`)
            nitroConfig.prerender = nitroConfig.prerender || {}
            nitroConfig.prerender.routes = [...new Set([...(nitroConfig.prerender.routes || []), ...routes])]
            console.log(`[nuxt] enumerated ${routes.length} /integrations/{id}/ routes for prerender`)
        }
    },

    studio: {
        route: '/_studio',
        repository: {
            provider: 'github',
            owner: 'FlowFuse',
            repo: 'website',
            branch: 'main',
            branchStrategy: 'feature-branch',
        }
    },

    content: {
        build: {
            markdown: {
                toc: {
                    depth: 4,
                    searchDepth: 4,
                },
                remarkPlugins: {
                    'handbook-links': { instance: remarkHandbookLinks },
                    'docs-links': { instance: remarkDocsLinks },
                    'remark-math': {},
                },
                rehypePlugins: {
                    'rehype-katex': {},
                },
            },
        },
    },

    vite: {
        optimizeDeps: {
            include: [
                '@vue/devtools-core',
                '@vue/devtools-kit',
            ],
        },
    },
    
    ui: {
        // Dark mode isn't implemented across the site yet. Disabling the color-mode
        // module here (rather than just setting a light `colorMode` preference) is
        // what actually stops Nuxt UI from switching to dark for visitors whose OS
        // prefers it — see https://ui.nuxt.com/docs/getting-started/integrations/color-mode/nuxt#configuration
        colorMode: false,
        theme: {
            colors: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'highlight']
        }
    },
    // Dev proxying to 11ty is handled by server/middleware/legacy.ts
    // to allow per-route exclusions as pages are migrated.
})
