// Redirects for retired 11ty routes, migrated here from the old `src/redirects.njk`
// (which rendered a Netlify `_redirects` file). Nuxt is now the front door for every
// route, so these are handled as native Nitro route rules instead of relying on
// Netlify's `_redirects` convention.
//
// TODO: longer term, consider moving these to netlify.toml so they run as edge-level
// redirects instead of inside the Nuxt/Nitro server — see the flowforge.com/flowfuze.com
// domain redirects already there for the pattern.
import type { NitroRouteRules } from 'nitropack'

export const redirects: Record<string, NitroRouteRules> = {
    '/handbook/product/': { redirect: { to: '/handbook/engineering/product/', statusCode: 301 } },
    '/handbook/product/blueprints/': { redirect: { to: '/handbook/engineering/blueprints/', statusCode: 301 } },
    '/handbook/engineering/product/blueprints/': { redirect: { to: '/handbook/engineering/blueprints/', statusCode: 301 } },
    '/handbook/engineering/product/vision/': { redirect: { to: '/handbook/engineering/product/', statusCode: 301 } },
    '/handbook/engineering/product/strategy/': { redirect: { to: '/handbook/engineering/product/', statusCode: 301 } },
    '/handbook/product/feedback/': { redirect: { to: '/handbook/engineering/product/feedback/', statusCode: 301 } },
    '/handbook/product/glossary/': { redirect: { to: '/handbook/engineering/product/glossary/', statusCode: 301 } },
    '/handbook/product/verticals/': { redirect: { to: '/handbook/engineering/product/verticals/', statusCode: 301 } },
    '/handbook/product/metrics/': { redirect: { to: '/handbook/engineering/product/metrics/', statusCode: 301 } },
    '/handbook/product/dashboard/': { redirect: { to: '/handbook/engineering/dashboard/', statusCode: 301 } },
    '/handbook/engineering/product/dashboard/': { redirect: { to: '/handbook/engineering/dashboard/', statusCode: 301 } },
    '/handbook/product/personas/': { redirect: { to: '/handbook/engineering/product/personas/', statusCode: 301 } },
    '/handbook/product/pricing/': { redirect: { to: '/handbook/engineering/product/pricing/', statusCode: 301 } },
    '/handbook/product/principles/': { redirect: { to: '/handbook/engineering/product/principles/', statusCode: 301 } },
    '/handbook/product/telemetry/': { redirect: { to: '/handbook/engineering/product/telemetry/', statusCode: 301 } },
    '/handbook/product/versioning/': { redirect: { to: '/handbook/engineering/product/versioning/', statusCode: 301 } },
    '/handbook/development/release/': { redirect: { to: '/handbook/engineering/releases/', statusCode: 301 } },
    '/blog/2023/05/Integrating-Modbus-with-Node-RED': { redirect: { to: '/blog/2023/05/integrating-modbus-with-node-red/', statusCode: 301 } },
    '/handbook/development/observability/': { redirect: { to: '/handbook/engineering/ops/observability/', statusCode: 301 } },
    '/handbook/development/staging/': { redirect: { to: '/handbook/engineering/ops/staging/', statusCode: 301 } },
    '/handbook/development/how-we-work/staging/': { redirect: { to: '/handbook/engineering/ops/staging/', statusCode: 301 } },
    '/handbook/development/how-we-work/security/': { redirect: { to: '/handbook/engineering/security/', statusCode: 301 } },
    '/handbook/development/how-we-work/packaging/': { redirect: { to: '/handbook/engineering/packaging/', statusCode: 301 } },
    '/handbook/development/how-we-work/contributing/': { redirect: { to: '/handbook/engineering/contributing/', statusCode: 301 } },
    '/handbook/development/how-we-work/': { redirect: { to: '/handbook/engineering/', statusCode: 301 } },
    '/platform/features/': { redirect: { to: '/product/', statusCode: 301 } },
    '/product/why-flowfuse/': { redirect: { to: '/product/', statusCode: 301 } },
    '/features/': { redirect: { to: '/product/', statusCode: 301 } },
    '/blog/2024/03/flowfuse-self-hosted-starter-resource-limits/': { redirect: { to: '/blog/2024/03/flowfuse-self-hosted-open-source-resource-limits/', statusCode: 301 } },
    '/unified-namespace/': { redirect: { to: '/use-cases/uns/', statusCode: 301 } },
    '/solutions/manufacturing/': { redirect: { to: '/use-cases/it-ot-middleware/', statusCode: 301 } },
    '/platform/cloud/': { redirect: { to: 'https://app.flowfuse.com/account/create/', statusCode: 301 } },
    '/solutions/device-management/': { redirect: { to: '/use-cases/edge-connectivity/', statusCode: 301 } },
    '/blueprints/manufacturing/andon-task/': { redirect: { to: '/blueprints/manufacturing/andon-system/', statusCode: 301 } },
    '/landing/technology-migration-1/': { redirect: { to: '/vs/kepware/', statusCode: 301 } },
    '/landing/technology-migration-2/': { redirect: { to: '/vs/kepware/', statusCode: 301 } },
    '/customer-stories/scaling-manufacturing-automation-with-flowfuse/': { redirect: { to: '/customer-stories/', statusCode: 301 } },
    '/blog/2025/10/the-ai-orchestation-hype/': { redirect: { to: '/blog/2025/10/the-ai-orchestration-hype/', statusCode: 301 } },
    '/node-red/core-nodes/mqtt/': { redirect: { to: '/node-red/core-nodes/mqtt-in/', statusCode: 301 } },
    '/blueprints/manufacturing/manufacturing-support-request/': { redirect: { to: '/blueprints/manufacturing/andon-system/', statusCode: 301 } },
    '/blueprints/other/remote-buffering/': { redirect: { to: '/blueprints/getting-started/store-and-forward/', statusCode: 301 } },
    '/vs/tulip/': { redirect: { to: '/landing/tulip/', statusCode: 301 } },
    '/product/security/': { redirect: { to: '/platform/security/', statusCode: 301 } },
    '/product/features/': { redirect: { to: '/product/', statusCode: 301 } },
    '/product/device-agent/': { redirect: { to: '/platform/device-agent/', statusCode: 301 } },
    '/product/dashboard/': { redirect: { to: '/platform/dashboard/', statusCode: 301 } },
    '/team/': { redirect: { to: '/about/', statusCode: 301 } },
    '/team': { redirect: { to: '/about/', statusCode: 301 } },
    '/docs/user/assistant/': { redirect: { to: '/docs/user/expert/', statusCode: 301 } },
    '/handbook/development/': { redirect: { to: '/handbook/engineering/', statusCode: 301 } },
    '/handbook/development/tools/': { redirect: { to: '/handbook/engineering/tools/', statusCode: 301 } },
    '/handbook/development/support/': { redirect: { to: '/handbook/engineering/support/', statusCode: 301 } },
    '/handbook/development/support/triage/': { redirect: { to: '/handbook/engineering/support/triage/', statusCode: 301 } },
    '/handbook/development/support/troubleshooting/': { redirect: { to: '/handbook/engineering/support/troubleshooting/', statusCode: 301 } },
    '/handbook/development/project-management/': { redirect: { to: '/handbook/engineering/project-management/', statusCode: 301 } },
    '/handbook/development/ops/deployment/': { redirect: { to: '/handbook/engineering/ops/deployment/', statusCode: 301 } },
    '/handbook/development/ops/dedicated/': { redirect: { to: '/handbook/engineering/ops/dedicated/', statusCode: 301 } },
    '/handbook/development/ops/incident-response/': { redirect: { to: '/handbook/engineering/ops/incident-response/', statusCode: 301 } },
    '/handbook/development/ops/production/': { redirect: { to: '/handbook/engineering/ops/production/', statusCode: 301 } },
    '/handbook/development/ops/self-hosted-assistant/': { redirect: { to: '/handbook/engineering/ops/self-hosted-assistant/', statusCode: 301 } },
    '/handbook/development/ops/production-stack-update/': { redirect: { to: '/handbook/engineering/ops/production-stack-update/', statusCode: 301 } },
    '/handbook/development/frontend/': { redirect: { to: '/handbook/engineering/frontend/', statusCode: 301 } },
    '/handbook/development/frontend/data-attributes/': { redirect: { to: '/handbook/engineering/frontend/data-attributes/', statusCode: 301 } },
    '/handbook/development/frontend/layouts/': { redirect: { to: '/handbook/engineering/frontend/layouts/', statusCode: 301 } },
    '/handbook/development/frontend/services/': { redirect: { to: '/handbook/engineering/frontend/services/', statusCode: 301 } },
    '/handbook/development/frontend/testing/': { redirect: { to: '/handbook/engineering/frontend/testing/', statusCode: 301 } },
    '/handbook/development/contributing/certified-nodes/': { redirect: { to: '/handbook/engineering/contributing/certified-nodes/', statusCode: 301 } },
    '/handbook/development/contributing/ff-tables/': { redirect: { to: '/handbook/engineering/contributing/ff-tables/', statusCode: 301 } },
    '/handbook/development/contributing/team-npm-registry/': { redirect: { to: '/handbook/engineering/contributing/team-npm-registry/', statusCode: 301 } },
    '/handbook/development/releases/dashboard-2/': { redirect: { to: '/handbook/engineering/releases/dashboard-2/', statusCode: 301 } },
    '/handbook/development/releases/process/': { redirect: { to: '/handbook/engineering/releases/process/', statusCode: 301 } },
    '/handbook/development/releases/digital-ocean/': { redirect: { to: '/handbook/engineering/releases/digital-ocean/', statusCode: 301 } },
    '/solutions/data-integration/': { redirect: { to: '/use-cases/data-integration/', statusCode: 301 } },
    '/solutions/edge-connectivity/': { redirect: { to: '/use-cases/edge-connectivity/', statusCode: 301 } },
    '/solutions/it-ot-middleware/': { redirect: { to: '/use-cases/it-ot-middleware/', statusCode: 301 } },
    '/solutions/mes/': { redirect: { to: '/use-cases/mes/', statusCode: 301 } },
    '/solutions/scada/': { redirect: { to: '/use-cases/scada/', statusCode: 301 } },
    '/solutions/uns/': { redirect: { to: '/use-cases/uns/', statusCode: 301 } },
    '/certified-nodes/': { redirect: { to: '/integrations/?certified=1', statusCode: 301 } },
    '/certified-nodes/**': { redirect: { to: '/integrations/?certified=1', statusCode: 301 } },
    '/docs/install/local/': { redirect: { to: '/docs/install/introduction/', statusCode: 301 } },
    '/docs/install/email_providers/': { redirect: { to: '/docs/install/email-providers/', statusCode: 301 } },
    '/docs/admin/user_management/': { redirect: { to: '/docs/admin/user-management/', statusCode: 301 } },
    '/docs/install/kubernetes/aws_terraform/': { redirect: { to: '/docs/install/kubernetes/aws-terraform/', statusCode: 301 } },
    '/cloud/': { redirect: { to: 'https://app.flowfuse.com/account/create/', statusCode: 301 } },
    '/legal/terms/': { redirect: { to: '/terms/', statusCode: 301 } },
    '/book-a-demo/': { redirect: { to: '/book-demo/', statusCode: 301 } },
    '/blog/2026/03/Rethinking-Edge-AIs-Core-Orchestration/': { redirect: { to: '/blog/2026/03/rethinking-edge-ais-core-orchestration/', statusCode: 301 } },
    '/education/': { redirect: { to: '/node-red/learn/', statusCode: 301 } },
    '/handbook/marketing/education/': { redirect: { to: '/handbook/marketing/', statusCode: 301 } },
    '/handbook/sales/org/account-executives/': { redirect: { to: '/handbook/sales/sales-team/', statusCode: 301 } },
    '/handbook/sales/org/': { redirect: { to: '/handbook/sales/', statusCode: 301 } },
    '/blog/2025/04/building-oee-dashboard-with-flowfuse-part-1/': { redirect: { to: '/blog/2025/04/what-is-an-oee-dashboard/', statusCode: 301 } },
    '/blog/2025/04/building-oee-dashboard-with-flowfuse-2/': { redirect: { to: '/blog/2025/04/build-manufacturing-oee-dashboard/', statusCode: 301 } },
    '/blog/2025/04/building-oee-dashboard-with-flowfuse-part-3/': { redirect: { to: '/blog/2025/04/design-and-scale-oee-dashboard/', statusCode: 301 } },
    '/sign-up/': { redirect: { to: 'https://app.flowfuse.com/account/create', statusCode: 301 } },

}
