// The Node-RED library moved from /node-red/** into /docs/**.
//
// Written out one path at a time rather than as a `/node-red/**` splat, because
// `/node-red/` itself did NOT move: it is a marketing page ("What is Node-RED?", with FAQ
// structured data) and a splat would swallow it along with the documentation below it.
// An explicit map also means a path that was never published cannot silently 301 into a
// 404, which is what a path-preserving splat would do for every typo and stale deep link.
//
// The core-node entries are derived from src/_data/coreNodes.json, since those pages were
// paginated out of that catalogue and never existed as files. Only real node slugs are
// listed: a bare category path like /node-red/core-nodes/common/ was never a page either,
// because the .njk templates were pagination-only. /node-red/core-nodes/function/ IS
// listed, because that was the Function node's own URL.
import type { NitroRouteRules } from 'nitropack'

const moved: Record<string, string> = {
    '/node-red/core-nodes/': '/docs/node-red/core-nodes/',
    '/node-red/core-nodes/batch/': '/docs/node-red/core-nodes/batch/',
    '/node-red/core-nodes/catch/': '/docs/node-red/core-nodes/catch/',
    '/node-red/core-nodes/change/': '/docs/node-red/core-nodes/change/',
    '/node-red/core-nodes/comment/': '/docs/node-red/core-nodes/comment/',
    '/node-red/core-nodes/complete/': '/docs/node-red/core-nodes/complete/',
    '/node-red/core-nodes/csv/': '/docs/node-red/core-nodes/csv/',
    '/node-red/core-nodes/debug/': '/docs/node-red/core-nodes/debug/',
    '/node-red/core-nodes/delay/': '/docs/node-red/core-nodes/delay/',
    '/node-red/core-nodes/exec/': '/docs/node-red/core-nodes/exec/',
    '/node-red/core-nodes/filter/': '/docs/node-red/core-nodes/filter/',
    '/node-red/core-nodes/function/': '/docs/node-red/core-nodes/function/',
    '/node-red/core-nodes/html/': '/docs/node-red/core-nodes/html/',
    '/node-red/core-nodes/http-in/': '/docs/node-red/core-nodes/http-in/',
    '/node-red/core-nodes/http-proxy/': '/docs/node-red/core-nodes/http-proxy/',
    '/node-red/core-nodes/http-request/': '/docs/node-red/core-nodes/http-request/',
    '/node-red/core-nodes/inject/': '/docs/node-red/core-nodes/inject/',
    '/node-red/core-nodes/join/': '/docs/node-red/core-nodes/join/',
    '/node-red/core-nodes/json/': '/docs/node-red/core-nodes/json/',
    '/node-red/core-nodes/link/': '/docs/node-red/core-nodes/link/',
    '/node-red/core-nodes/mqtt-in/': '/docs/node-red/core-nodes/mqtt-in/',
    '/node-red/core-nodes/mqtt-out/': '/docs/node-red/core-nodes/mqtt-out/',
    '/node-red/core-nodes/range/': '/docs/node-red/core-nodes/range/',
    '/node-red/core-nodes/read-file/': '/docs/node-red/core-nodes/read-file/',
    '/node-red/core-nodes/sort/': '/docs/node-red/core-nodes/sort/',
    '/node-red/core-nodes/split/': '/docs/node-red/core-nodes/split/',
    '/node-red/core-nodes/status/': '/docs/node-red/core-nodes/status/',
    '/node-red/core-nodes/switch/': '/docs/node-red/core-nodes/switch/',
    '/node-red/core-nodes/tcp-in/': '/docs/node-red/core-nodes/tcp-in/',
    '/node-red/core-nodes/template/': '/docs/node-red/core-nodes/template/',
    '/node-red/core-nodes/tls/': '/docs/node-red/core-nodes/tls/',
    '/node-red/core-nodes/trigger/': '/docs/node-red/core-nodes/trigger/',
    '/node-red/core-nodes/udp-in/': '/docs/node-red/core-nodes/udp-in/',
    '/node-red/core-nodes/udp-out/': '/docs/node-red/core-nodes/udp-out/',
    '/node-red/core-nodes/unknown/': '/docs/node-red/core-nodes/unknown/',
    '/node-red/core-nodes/websocket/': '/docs/node-red/core-nodes/websocket/',
    '/node-red/core-nodes/write-file/': '/docs/node-red/core-nodes/write-file/',
    '/node-red/core-nodes/xml/': '/docs/node-red/core-nodes/xml/',
    '/node-red/core-nodes/yaml/': '/docs/node-red/core-nodes/yaml/',
    '/node-red/database/': '/docs/node-red/database/',
    '/node-red/database/dynamodb/': '/docs/node-red/database/dynamodb/',
    '/node-red/database/firebase/': '/docs/node-red/database/firebase/',
    '/node-red/database/influxdb/': '/docs/node-red/database/influxdb/',
    '/node-red/database/mongodb/': '/docs/node-red/database/mongodb/',
    '/node-red/database/mysql/': '/docs/node-red/database/mysql/',
    '/node-red/database/postgresql/': '/docs/node-red/database/postgresql/',
    '/node-red/database/redis/': '/docs/node-red/database/redis/',
    '/node-red/database/sqlite/': '/docs/node-red/database/sqlite/',
    '/node-red/database/timescaledb/': '/docs/node-red/database/timescaledb/',
    '/node-red/flowfuse/': '/docs/flowfuse-nodes/',
    '/node-red/flowfuse/ai/': '/docs/flowfuse-nodes/ai/',
    '/node-red/flowfuse/ai/depth-estimation/': '/docs/flowfuse-nodes/ai/depth-estimation/',
    '/node-red/flowfuse/ai/image-classification/': '/docs/flowfuse-nodes/ai/image-classification/',
    '/node-red/flowfuse/ai/llm-nodes/': '/docs/flowfuse-nodes/ai/llm-nodes/',
    '/node-red/flowfuse/ai/object-detection/': '/docs/flowfuse-nodes/ai/object-detection/',
    '/node-red/flowfuse/ai/onxx/': '/docs/flowfuse-nodes/ai/onxx/',
    '/node-red/flowfuse/edge/': '/docs/flowfuse-nodes/edge/',
    '/node-red/flowfuse/edge/cip-suite/': '/docs/flowfuse-nodes/edge/cip-suite/',
    '/node-red/flowfuse/edge/modbus/': '/docs/flowfuse-nodes/edge/modbus/',
    '/node-red/flowfuse/edge/opcua/': '/docs/flowfuse-nodes/edge/opcua/',
    '/node-red/flowfuse/edge/rtsp/': '/docs/flowfuse-nodes/edge/rtsp/',
    '/node-red/flowfuse/flowfuse-tables/': '/docs/flowfuse-nodes/flowfuse-tables/',
    '/node-red/flowfuse/flowfuse-tables/query/': '/docs/flowfuse-nodes/flowfuse-tables/query/',
    '/node-red/flowfuse/hub/': '/docs/flowfuse-nodes/hub/',
    '/node-red/flowfuse/hub/redis/': '/docs/flowfuse-nodes/hub/redis/',
    '/node-red/flowfuse/mcp/': '/docs/flowfuse-nodes/mcp/',
    '/node-red/flowfuse/mcp/mcp-prompt/': '/docs/flowfuse-nodes/mcp/mcp-prompt/',
    '/node-red/flowfuse/mcp/mcp-resource/': '/docs/flowfuse-nodes/mcp/mcp-resource/',
    '/node-red/flowfuse/mcp/mcp-response/': '/docs/flowfuse-nodes/mcp/mcp-response/',
    '/node-red/flowfuse/mcp/mcp-tool/': '/docs/flowfuse-nodes/mcp/mcp-tool/',
    '/node-red/flowfuse/mqtt/': '/docs/flowfuse-nodes/mqtt/',
    '/node-red/flowfuse/mqtt/mqtt-in/': '/docs/flowfuse-nodes/mqtt/mqtt-in/',
    '/node-red/flowfuse/mqtt/mqtt-out/': '/docs/flowfuse-nodes/mqtt/mqtt-out/',
    '/node-red/getting-started/': '/docs/node-red/getting-started/',
    '/node-red/getting-started/date-and-time/': '/docs/node-red/getting-started/date-and-time/',
    '/node-red/getting-started/editor/': '/docs/node-red/getting-started/editor/',
    '/node-red/getting-started/editor/header/': '/docs/node-red/getting-started/editor/header/',
    '/node-red/getting-started/editor/palette/': '/docs/node-red/getting-started/editor/palette/',
    '/node-red/getting-started/editor/sidebar/': '/docs/node-red/getting-started/editor/sidebar/',
    '/node-red/getting-started/editor/workspace/': '/docs/node-red/getting-started/editor/workspace/',
    '/node-red/getting-started/library/': '/docs/node-red/getting-started/library/',
    '/node-red/getting-started/node-red-android/': '/docs/node-red/getting-started/node-red-android/',
    '/node-red/getting-started/node-red-messages/': '/docs/node-red/getting-started/node-red-messages/',
    '/node-red/getting-started/node-red-port/': '/docs/node-red/getting-started/node-red-port/',
    '/node-red/getting-started/programming/': '/docs/node-red/getting-started/programming/',
    '/node-red/getting-started/programming/data-tranformation/': '/docs/node-red/getting-started/programming/data-tranformation/',
    '/node-red/getting-started/programming/debugging-flows/': '/docs/node-red/getting-started/programming/debugging-flows/',
    '/node-red/getting-started/programming/if-else/': '/docs/node-red/getting-started/programming/if-else/',
    '/node-red/getting-started/programming/loop/': '/docs/node-red/getting-started/programming/loop/',
    '/node-red/getting-started/string/': '/docs/node-red/getting-started/string/',
    '/node-red/getting-started/update-node-red/': '/docs/node-red/getting-started/update-node-red/',
    '/node-red/hardware/': '/docs/node-red/hardware/',
    '/node-red/hardware/armxy-bl340/': '/docs/node-red/hardware/armxy-bl340/',
    '/node-red/hardware/opto-22-groove-rio-7-mm2001-10/': '/docs/node-red/hardware/opto-22-groove-rio-7-mm2001-10/',
    '/node-red/hardware/raspberry-pi-4/': '/docs/node-red/hardware/raspberry-pi-4/',
    '/node-red/hardware/raspberry-pi-5/': '/docs/node-red/hardware/raspberry-pi-5/',
    '/node-red/hardware/robustel-eg5120/': '/docs/node-red/hardware/robustel-eg5120/',
    '/node-red/hardware/siemens-iot-2050/': '/docs/node-red/hardware/siemens-iot-2050/',
    '/node-red/integration-technologies/': '/docs/node-red/integration-technologies/',
    '/node-red/integration-technologies/graphql/': '/docs/node-red/integration-technologies/graphql/',
    '/node-red/integration-technologies/rest/': '/docs/node-red/integration-technologies/rest/',
    '/node-red/integration-technologies/webhook/': '/docs/node-red/integration-technologies/webhook/',
    '/node-red/keyboard/': '/docs/node-red/keyboard/',
    '/node-red/learn/': '/docs/node-red/',
    '/node-red/notification/': '/docs/node-red/notification/',
    '/node-red/notification/discord/': '/docs/node-red/notification/discord/',
    '/node-red/notification/email/': '/docs/node-red/notification/email/',
    '/node-red/notification/telegram/': '/docs/node-red/notification/telegram/',
    '/node-red/peripheral/': '/docs/node-red/peripheral/',
    '/node-red/peripheral/ardiuno/': '/docs/node-red/peripheral/ardiuno/',
    '/node-red/peripheral/barcodescanner/': '/docs/node-red/peripheral/barcodescanner/',
    '/node-red/peripheral/esp32/': '/docs/node-red/peripheral/esp32/',
    '/node-red/peripheral/webcam/': '/docs/node-red/peripheral/webcam/',
    '/node-red/protocol/': '/docs/node-red/protocol/',
    '/node-red/protocol/amqp/': '/docs/node-red/protocol/amqp/',
    '/node-red/protocol/lwm2m/': '/docs/node-red/protocol/lwm2m/',
    '/node-red/protocol/modbus/': '/docs/node-red/protocol/modbus/',
    '/node-red/protocol/mqtt/': '/docs/node-red/protocol/mqtt/',
    '/node-red/protocol/opc-ua/': '/docs/node-red/protocol/opc-ua/',
    '/node-red/protocol/websocket/': '/docs/node-red/protocol/websocket/',
    '/node-red/terminology/': '/docs/node-red/terminology/',
}

export const nodeRedRedirects: Record<string, NitroRouteRules> = Object.fromEntries(
    Object.entries(moved).map(([from, to]) => [from, { redirect: { to, statusCode: 301 } }])
)
