/**
 * Writes src/_data/latestPosts.json - the newest blog posts, for the Blog panel
 * in the header nav.
 *
 * Why a generated file rather than each renderer querying for itself: the header
 * is drawn by two independent templates from one set of shared data (see
 * src/_data/chrome.json). 11ty could read the posts through src/_data/blogPosts.js
 * and Nuxt through its `blog` content collection, but that is two queries with
 * two sort orders and two definitions of "published", and the two headers would
 * drift the first time one of them changed. This is one file, imported by both,
 * exactly as chrome.json is.
 *
 * The output is committed so a checkout renders the nav without running anything.
 * It is regenerated as the first step of both production builds, so what ships is
 * never the committed snapshot - see the `blog:latest` script in package.json.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..')
const blogDir = join(repo, 'src', 'blog')
const outFile = join(repo, 'src', '_data', 'latestPosts.json')

// How many rows the Blog panel's first column shows.
const COUNT = 5

function walk (dir) {
    let files = []
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name)
        if (entry.isDirectory()) files = files.concat(walk(full))
        else if (entry.name.endsWith('.md')) files.push(full)
    }
    return files
}

const now = new Date()

const posts = walk(blogDir)
    .map((file) => {
        const raw = readFileSync(file, 'utf-8')
        const match = raw.match(/^---[ \t]*\r?\n([\s\S]*?)\r?\n---/)
        if (!match) return null
        const data = yaml.load(match[1]) || {}
        if (!data.title || !data.date) return null
        const slug = relative(blogDir, file).replace(/\.md$/, '').replace(/\\/g, '/')
        return { title: String(data.title), href: `/blog/${slug}/`, date: new Date(data.date) }
    })
    .filter(Boolean)
    // A post dated in the future is scheduled, not published. The nav must never
    // advertise one: unlike the blog index, which is allowed to preview them in a
    // dev build, this file is baked into every page's header.
    .filter(post => post.date <= now)
    .sort((a, b) => b.date - a.date)
    .slice(0, COUNT)
    .map(post => ({ label: post.title, href: post.href, date: post.date.toISOString().slice(0, 10) }))

if (!posts.length) throw new Error('build_latest_posts: no published posts found in src/blog')

writeFileSync(outFile, JSON.stringify({
    _comment: 'Generated by scripts/build_latest_posts.mjs. Do not edit by hand; run `npm run blog:latest`.',
    posts,
}, null, 4) + '\n')

console.info(`[latest-posts] wrote ${posts.length} posts to src/_data/latestPosts.json`)
