#!/usr/bin/env python3
"""Regenerate nuxt/utils/siteArt.ts from the icon keys the site actually references.

<SiteArt> inlines an SVG from nuxt/assets/icons/ verbatim, which is what
page content that used a bare {% include %} needs. The registry is written out rather
than globbed, so the bundle carries only the icons in use - an eager glob of that
directory inlines ~137 KB, most of it unused art.

Keeping it hand-maintained across ~50 keys is not realistic, so this scans for every
key that is referenced and rewrites the file. Run it after adding a page that names a
new icon; the build fails loudly on a missing import, and <SiteArt> warns in dev on a
key the registry does not have.

Usage: python3 gen-site-art.py <repo-root>
"""
import re
import sys
from pathlib import Path

ICON_DIR = Path('nuxt/assets/icons')


def referenced_keys(root: Path) -> tuple[set[str], set[str]]:
    """Returns (explicit, harvested).

    `explicit` are literal <SiteArt name="x" /> uses - a missing file there is a broken
    page, so it fails the run. `harvested` are svgPath:/icon: values in content and page
    consts, which a renderer *may* pass to SiteArt but may equally resolve some other way
    (contact-us has its own icon map, for one), so a miss there is only reported.
    """
    explicit: set[str] = set()
    keys: set[str] = set()
    for vue in list((root / 'nuxt/pages').rglob('*.vue')) + list((root / 'nuxt/components').rglob('*.vue')):
        explicit.update(re.findall(r'<SiteArt\s+name="([a-z0-9-]+)"', vue.read_text()))
    # svgPath:/icon: keys in the content collections, which the renderers pass to SiteArt,
    # and the same keys declared in a page's own const arrays. Both quote styles: YAML
    # here is double-quoted, the .vue consts are single-quoted.
    sources = list((root / 'nuxt/content').rglob('*.yml'))
    sources += list((root / 'nuxt/pages').rglob('*.vue'))
    sources += list((root / 'nuxt/components').rglob('*.vue'))
    for f in sources:
        text = f.read_text()
        keys.update(re.findall(r'''(?:svgPath|icon|eyebrowIcon|badge):\s*["']([a-z0-9-]+)["']''', text))
    # An "i-heroicons-x" / "i-lucide-x" value is a <UIcon> name resolved from an installed
    # icon set, not a file in this repo, so it is not SiteArt's to provide.
    return explicit, {key for key in keys if not key.startswith('i-')}


def ident(key: str) -> str:
    return 'a' + ''.join(part.capitalize() for part in key.split('-'))


def main() -> None:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else '.')
    explicit, harvested = referenced_keys(root)
    keys = explicit | harvested

    # Keys that resolve through NavIcon (the navoption/ffIconLg wrapper) or a hand-written
    # Vue icon component are not SiteArt's job.
    nav = root / 'nuxt/utils/navIcons.ts'
    nav_keys = set(re.findall(r"^    '([a-z0-9-]+)':", nav.read_text(), re.M)) if nav.exists() else set()

    usable, missing = [], []
    for key in sorted(keys):
        if (root / ICON_DIR / f'{key}.svg').exists():
            usable.append(key)
        else:
            missing.append(key)

    header = '''// SVG files that page content included raw, with no wrapper: {% include "components/icons/
// x.svg" %} rather than the `navoption`/`ffIconLg` shortcodes that NavIcon reproduces.
//
// They cannot go through NavIcon or an <img>:
//  - NavIcon wraps its payload in an outer <svg> carrying a fixed ff-icon size class,
//    which would override the size the caller's box sets.
//  - <img> breaks `currentColor`, and most of these are coloured by their container.
//
// GENERATED by scripts/gen-site-art.py from the keys the pages and content collections
// actually reference, so the bundle carries only what is used - an eager glob of that
// directory inlines ~137 KB, most of it unused art. Re-run it after adding a page that
// names a new icon.
'''
    lines = [header]
    for key in usable:
        lines.append(f"import {ident(key)} from '../../{ICON_DIR}/{key}.svg?raw'")
    lines.append('\nexport const siteArt: Record<string, string> = {')
    for key in usable:
        lines.append(f"    '{key}': {ident(key)},")
    lines.append('}\n')

    out = root / 'nuxt/utils/siteArt.ts'
    out.write_text('\n'.join(lines))
    print(f'{out}: {len(usable)} icons')
    also_in_nav = sorted(set(usable) & nav_keys)
    if also_in_nav:
        print(f'  (also in navIcons, which is fine - different wrapper: {", ".join(also_in_nav[:6])}…)')
    broken = [key for key in missing if key in explicit]
    if missing:
        print(f'  no SVG file (resolved elsewhere, not bundled here): {", ".join(missing)}')
    if broken:
        print(f'  ERROR: <SiteArt> is asked for these and there is no file: {", ".join(broken)}')
        sys.exit(1)


if __name__ == '__main__':
    main()
