// SVG files that page content included raw, with no wrapper: {% include "components/icons/
// x.svg" %} rather than the `navoption`/`ffIconLg` shortcodes that NavIcon reproduces.
//
// They cannot go through NavIcon or an <img>:
//  - NavIcon wraps its payload in an outer <svg> carrying a fixed ff-icon size class,
//    which would override the size the caller's box sets.
//  - <img> breaks `currentColor`, and most of these are coloured by their container.
//
// GENERATED by scripts/gen-site-art.py from the keys the pages and content collections
// actually reference, so the bundle carries only what is used - an eager glob of that
// directory inlines ~137 KB, most of it unused art. Re-run it after adding a page that
// names a new icon.

import aAcademicCap from '../assets/icons/academic-cap.svg?raw'
import aAdjustmentsHorizontal from '../assets/icons/adjustments-horizontal.svg?raw'
import aAdjustmentsVertical from '../assets/icons/adjustments-vertical.svg?raw'
import aAirGappedDeployment from '../assets/icons/air-gapped-deployment.svg?raw'
import aAirplane from '../assets/icons/airplane.svg?raw'
import aArchiveBoxXMark from '../assets/icons/archive-box-x-mark.svg?raw'
import aArrowLongRight from '../assets/icons/arrow-long-right.svg?raw'
import aArrowPath from '../assets/icons/arrow-path.svg?raw'
import aArrowPathRoundedSquare from '../assets/icons/arrow-path-rounded-square.svg?raw'
import aArrowSmallDown from '../assets/icons/arrow-small-down.svg?raw'
import aArrowTopRightOnSquare from '../assets/icons/arrow-top-right-on-square.svg?raw'
import aArrowTrendingUp from '../assets/icons/arrow-trending-up.svg?raw'
import aArrows from '../assets/icons/arrows.svg?raw'
import aArrowsPointingOut from '../assets/icons/arrows-pointing-out.svg?raw'
import aArrowsRightLeft from '../assets/icons/arrows-right-left.svg?raw'
import aAuditLogs from '../assets/icons/audit-logs.svg?raw'
import aBellAlert from '../assets/icons/bell-alert.svg?raw'
import aBolt from '../assets/icons/bolt.svg?raw'
import aBookOpen from '../assets/icons/book-open.svg?raw'
import aBuildingOffice2 from '../assets/icons/building-office-2.svg?raw'
import aCalendar from '../assets/icons/calendar.svg?raw'
import aCamera from '../assets/icons/camera.svg?raw'
import aCar from '../assets/icons/car.svg?raw'
import aCertificate from '../assets/icons/certificate.svg?raw'
import aCertifiedNode from '../assets/icons/certified-node.svg?raw'
import aChart from '../assets/icons/chart.svg?raw'
import aChatBubbleBottomCenterText from '../assets/icons/chat-bubble-bottom-center-text.svg?raw'
import aChatBubbleLeftRightSm from '../assets/icons/chat-bubble-left-right-sm.svg?raw'
import aCheckBadge from '../assets/icons/check-badge.svg?raw'
import aCheckCircle from '../assets/icons/check-circle.svg?raw'
import aChevronDown from '../assets/icons/chevron-down.svg?raw'
import aChevronLeft from '../assets/icons/chevron-left.svg?raw'
import aChevronRight from '../assets/icons/chevron-right.svg?raw'
import aChevronRightSm from '../assets/icons/chevron-right-sm.svg?raw'
import aChip from '../assets/icons/chip.svg?raw'
import aCircleStack from '../assets/icons/circle-stack.svg?raw'
import aClipList from '../assets/icons/clip-list.svg?raw'
import aClipboardDocumentCheck from '../assets/icons/clipboard-document-check.svg?raw'
import aClock from '../assets/icons/clock.svg?raw'
import aCloud from '../assets/icons/cloud.svg?raw'
import aCodeBracket from '../assets/icons/code-bracket.svg?raw'
import aCodeblock from '../assets/icons/codeblock.svg?raw'
import aCog from '../assets/icons/cog.svg?raw'
import aCog6Tooth from '../assets/icons/cog-6-tooth.svg?raw'
import aComputerDesktop from '../assets/icons/computer-desktop.svg?raw'
import aCubeTransparent from '../assets/icons/cube-transparent.svg?raw'
import aCursorArrowRays from '../assets/icons/cursor-arrow-rays.svg?raw'
import aData from '../assets/icons/data.svg?raw'
import aDatabase from '../assets/icons/database.svg?raw'
import aDocumentArrowUp from '../assets/icons/document-arrow-up.svg?raw'
import aDocumentChartBar from '../assets/icons/document-chart-bar.svg?raw'
import aDocumentCheck from '../assets/icons/document-check.svg?raw'
import aDocumentText from '../assets/icons/document-text.svg?raw'
import aEye from '../assets/icons/eye.svg?raw'
import aEyeSlash from '../assets/icons/eye-slash.svg?raw'
import aFactory from '../assets/icons/factory.svg?raw'
import aGlobeAlt from '../assets/icons/globe-alt.svg?raw'
import aHandRaised from '../assets/icons/hand-raised.svg?raw'
import aLayers from '../assets/icons/layers.svg?raw'
import aLifebuoy from '../assets/icons/lifebuoy.svg?raw'
import aLightBulb from '../assets/icons/light-bulb.svg?raw'
import aLink from '../assets/icons/link.svg?raw'
import aLinkSlash from '../assets/icons/link-slash.svg?raw'
import aLock from '../assets/icons/lock.svg?raw'
import aLockClosed from '../assets/icons/lock-closed.svg?raw'
import aLockOpen from '../assets/icons/lock-open.svg?raw'
import aPin from '../assets/icons/pin.svg?raw'
import aPinSlash from '../assets/icons/pin-slash.svg?raw'
import aPulse from '../assets/icons/pulse.svg?raw'
import aPuzzlePiece from '../assets/icons/puzzle-piece.svg?raw'
import aQueueList from '../assets/icons/queue-list.svg?raw'
import aRectangleStack from '../assets/icons/rectangle-stack.svg?raw'
import aRocketLaunch from '../assets/icons/rocket-launch.svg?raw'
import aRoleBasedAccess from '../assets/icons/role-based-access.svg?raw'
import aServerStack from '../assets/icons/server-stack.svg?raw'
import aShare from '../assets/icons/share.svg?raw'
import aShieldCheck from '../assets/icons/shield-check.svg?raw'
import aShieldExclamation from '../assets/icons/shield-exclamation.svg?raw'
import aSingleSignOn from '../assets/icons/single-sign-on.svg?raw'
import aSnowflake from '../assets/icons/snowflake.svg?raw'
import aSparkles from '../assets/icons/sparkles.svg?raw'
import aSquares2x2 from '../assets/icons/squares-2x2.svg?raw'
import aSquaresPlus from '../assets/icons/squares-plus.svg?raw'
import aTargetView from '../assets/icons/target-view.svg?raw'
import aUns from '../assets/icons/uns.svg?raw'
import aUserGroup from '../assets/icons/user-group.svg?raw'
import aUsers from '../assets/icons/users.svg?raw'
import aWifi from '../assets/icons/wifi.svg?raw'
import aWindTurbine from '../assets/icons/wind-turbine.svg?raw'
import aWrenchScrewdriver from '../assets/icons/wrench-screwdriver.svg?raw'

export const siteArt: Record<string, string> = {
    'academic-cap': aAcademicCap,
    'adjustments-horizontal': aAdjustmentsHorizontal,
    'adjustments-vertical': aAdjustmentsVertical,
    'air-gapped-deployment': aAirGappedDeployment,
    'airplane': aAirplane,
    'archive-box-x-mark': aArchiveBoxXMark,
    'arrow-long-right': aArrowLongRight,
    'arrow-path': aArrowPath,
    'arrow-path-rounded-square': aArrowPathRoundedSquare,
    'arrow-small-down': aArrowSmallDown,
    'arrow-top-right-on-square': aArrowTopRightOnSquare,
    'arrow-trending-up': aArrowTrendingUp,
    'arrows': aArrows,
    'arrows-pointing-out': aArrowsPointingOut,
    'arrows-right-left': aArrowsRightLeft,
    'audit-logs': aAuditLogs,
    'bell-alert': aBellAlert,
    'bolt': aBolt,
    'book-open': aBookOpen,
    'building-office-2': aBuildingOffice2,
    'calendar': aCalendar,
    'camera': aCamera,
    'car': aCar,
    'certificate': aCertificate,
    'certified-node': aCertifiedNode,
    'chart': aChart,
    'chat-bubble-bottom-center-text': aChatBubbleBottomCenterText,
    'chat-bubble-left-right-sm': aChatBubbleLeftRightSm,
    'check-badge': aCheckBadge,
    'check-circle': aCheckCircle,
    'chevron-down': aChevronDown,
    'chevron-left': aChevronLeft,
    'chevron-right': aChevronRight,
    'chevron-right-sm': aChevronRightSm,
    'chip': aChip,
    'circle-stack': aCircleStack,
    'clip-list': aClipList,
    'clipboard-document-check': aClipboardDocumentCheck,
    'clock': aClock,
    'cloud': aCloud,
    'code-bracket': aCodeBracket,
    'codeblock': aCodeblock,
    'cog': aCog,
    'cog-6-tooth': aCog6Tooth,
    'computer-desktop': aComputerDesktop,
    'cube-transparent': aCubeTransparent,
    'cursor-arrow-rays': aCursorArrowRays,
    'data': aData,
    'database': aDatabase,
    'document-arrow-up': aDocumentArrowUp,
    'document-chart-bar': aDocumentChartBar,
    'document-check': aDocumentCheck,
    'document-text': aDocumentText,
    'eye': aEye,
    'eye-slash': aEyeSlash,
    'factory': aFactory,
    'globe-alt': aGlobeAlt,
    'hand-raised': aHandRaised,
    'layers': aLayers,
    'lifebuoy': aLifebuoy,
    'light-bulb': aLightBulb,
    'link': aLink,
    'link-slash': aLinkSlash,
    'lock': aLock,
    'lock-closed': aLockClosed,
    'lock-open': aLockOpen,
    'pin': aPin,
    'pin-slash': aPinSlash,
    'pulse': aPulse,
    'puzzle-piece': aPuzzlePiece,
    'queue-list': aQueueList,
    'rectangle-stack': aRectangleStack,
    'rocket-launch': aRocketLaunch,
    'role-based-access': aRoleBasedAccess,
    'server-stack': aServerStack,
    'share': aShare,
    'shield-check': aShieldCheck,
    'shield-exclamation': aShieldExclamation,
    'single-sign-on': aSingleSignOn,
    'snowflake': aSnowflake,
    'sparkles': aSparkles,
    'squares-2x2': aSquares2x2,
    'squares-plus': aSquaresPlus,
    'target-view': aTargetView,
    'uns': aUns,
    'user-group': aUserGroup,
    'users': aUsers,
    'wifi': aWifi,
    'wind-turbine': aWindTurbine,
    'wrench-screwdriver': aWrenchScrewdriver,
}
