name: Compress images
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    if: github.repository == 'FlowFuse/website' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout Branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@9d037c06280028c110ff61c433ad4dc7d33c3c43 # 1.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # For non-Pull Requests, run in compressOnly mode and we'll PR after.
          compressOnly: ${{ github.event_name != 'pull_request' }}
          pngQuality: '100'
          ignorePaths: 'nuxt/**'
